//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Agent_Website_Localization.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SetupModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetupModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Agent_Website_Localization.Setup.SetupModel", typeof(SetupModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adı.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Telefon No.
        /// </summary>
        public static string CustomerPhoneNo {
            get {
                return ResourceManager.GetString("CustomerPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Tipi.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Açıklaması.
        /// </summary>
        public static string FaultCodes {
            get {
                return ResourceManager.GetString("FaultCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Telefon No.
        /// </summary>
        public static string PSTN {
            get {
                return ResourceManager.GetString("PSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randevu Tarihi.
        /// </summary>
        public static string ReservationDate {
            get {
                return ResourceManager.GetString("ReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurulum Adresi.
        /// </summary>
        public static string SetupAddress {
            get {
                return ResourceManager.GetString("SetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenlenme Tarihi.
        /// </summary>
        public static string TaskIssueDate {
            get {
                return ResourceManager.GetString("TaskIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Numarası.
        /// </summary>
        public static string TaskNo {
            get {
                return ResourceManager.GetString("TaskNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Durumu .
        /// </summary>
        public static string TaskStatus {
            get {
                return ResourceManager.GetString("TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görev Türü.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL No.
        /// </summary>
        public static string XDSLNo {
            get {
                return ResourceManager.GetString("XDSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL Tipi.
        /// </summary>
        public static string XDSLType {
            get {
                return ResourceManager.GetString("XDSLType", resourceCulture);
            }
        }
    }
}
