//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterISS_Agent_Website_Localization.Customer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterISS_Agent_Website_Localization.Customer.CustomerModel", typeof(CustomerModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Adresi, Kurulum Adresi ile Aynı.
        /// </summary>
        public static string BillingAddressSameSetupAddress {
            get {
                return ResourceManager.GetString("BillingAddressSameSetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura Dönemi.
        /// </summary>
        public static string BillingPeriodId {
            get {
                return ResourceManager.GetString("BillingPeriodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yeri.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Tipini Seçiniz.
        /// </summary>
        public static string CardTypeId {
            get {
                return ResourceManager.GetString("CardTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkezi Sistem Numarası.
        /// </summary>
        public static string CentralSystemNo {
            get {
                return ResourceManager.GetString("CentralSystemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri GSM Numaranızı Yazınız.
        /// </summary>
        public static string ContactPhoneNo {
            get {
                return ResourceManager.GetString("ContactPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adresi, Kurulum Adresi ile Aynı.
        /// </summary>
        public static string CorporativeCompanyAddressSameSetupAddress {
            get {
                return ResourceManager.GetString("CorporativeCompanyAddressSameSetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili İkamet Adresi, Kurulum Adresi ile Aynı.
        /// </summary>
        public static string CorporativeResidencyAddressSameSetupAddress {
            get {
                return ResourceManager.GetString("CorporativeResidencyAddressSameSetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online işlem merkezi için Dil Seçimi.
        /// </summary>
        public static string CultureCustomer {
            get {
                return ResourceManager.GetString("CultureCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adı.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri İkamet Adresi, Kurulum Adresi ile Aynı.
        /// </summary>
        public static string CustomerResidanceAddressSameSetupAddress {
            get {
                return ResourceManager.GetString("CustomerResidanceAddressSameSetupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Durumu.
        /// </summary>
        public static string CustomerState {
            get {
                return ResourceManager.GetString("CustomerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Tipi.
        /// </summary>
        public static string CustomerTypeId {
            get {
                return ResourceManager.GetString("CustomerTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriliş Tarihi (Gün).
        /// </summary>
        public static string DateOfIssueDay {
            get {
                return ResourceManager.GetString("DateOfIssueDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriliş Tarihi (Ay).
        /// </summary>
        public static string DateOfIssueMonth {
            get {
                return ResourceManager.GetString("DateOfIssueMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veriliş Tarihi (Yıl).
        /// </summary>
        public static string DateOfIssueYear {
            get {
                return ResourceManager.GetString("DateOfIssueYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Doğum Yeri.
        /// </summary>
        public static string ExecutiveBirthPlace {
            get {
                return ResourceManager.GetString("ExecutiveBirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Baba Adı.
        /// </summary>
        public static string ExecutiveFathersName {
            get {
                return ResourceManager.GetString("ExecutiveFathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Anne Kızlık Soyadı.
        /// </summary>
        public static string ExecutiveMothersMaidenName {
            get {
                return ResourceManager.GetString("ExecutiveMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Anne Adı.
        /// </summary>
        public static string ExecutiveMothersName {
            get {
                return ResourceManager.GetString("ExecutiveMothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Adı.
        /// </summary>
        public static string ExecutiveName {
            get {
                return ResourceManager.GetString("ExecutiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Uyruğu.
        /// </summary>
        public static string ExecutiveNationalityId {
            get {
                return ResourceManager.GetString("ExecutiveNationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Telefon No.
        /// </summary>
        public static string ExecutivePhoneNo {
            get {
                return ResourceManager.GetString("ExecutivePhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Mesleği.
        /// </summary>
        public static string ExecutiveProfessionId {
            get {
                return ResourceManager.GetString("ExecutiveProfessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili İkamet Adresi.
        /// </summary>
        public static string ExecutiveResidencyAddress {
            get {
                return ResourceManager.GetString("ExecutiveResidencyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Cinsiyeti.
        /// </summary>
        public static string ExecutiveSexId {
            get {
                return ResourceManager.GetString("ExecutiveSexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Soyadı.
        /// </summary>
        public static string ExecutiveSurname {
            get {
                return ResourceManager.GetString("ExecutiveSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Geçerlilik Tarihi (Gün).
        /// </summary>
        public static string ExpiryDay {
            get {
                return ResourceManager.GetString("ExpiryDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Geçerlilik Tarihi (Ay).
        /// </summary>
        public static string ExpiryMonth {
            get {
                return ResourceManager.GetString("ExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik Geçerlilik Tarihi (Yıl).
        /// </summary>
        public static string ExpiryYear {
            get {
                return ResourceManager.GetString("ExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba Adı.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Telefonunuz Var mı?.
        /// </summary>
        public static string HavePSTNId {
            get {
                return ResourceManager.GetString("HavePSTNId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadı.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tarihi.
        /// </summary>
        public static string MembershipDate {
            get {
                return ResourceManager.GetString("MembershipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne Kızlık Soyadı.
        /// </summary>
        public static string MothersMaidenName {
            get {
                return ResourceManager.GetString("MothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anne Adı.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyruk.
        /// </summary>
        public static string NationalityId {
            get {
                return ResourceManager.GetString("NationalityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köy/Mahalle.
        /// </summary>
        public static string Neighbourhood {
            get {
                return ResourceManager.GetString("Neighbourhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer Telefon Numaraları.
        /// </summary>
        public static string OtherPhoneNos {
            get {
                return ResourceManager.GetString("OtherPhoneNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aile Sıra No.
        /// </summary>
        public static string PageNo {
            get {
                return ResourceManager.GetString("PageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarife Seçimi.
        /// </summary>
        public static string PartnerTariffID {
            get {
                return ResourceManager.GetString("PartnerTariffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasaport No.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verildiği Yer.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meslek.
        /// </summary>
        public static string ProfessionId {
            get {
                return ResourceManager.GetString("ProfessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev Telefonu Numarası.
        /// </summary>
        public static string PSTNNo {
            get {
                return ResourceManager.GetString("PSTNNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru Türü.
        /// </summary>
        public static string RegistrationType {
            get {
                return ResourceManager.GetString("RegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıra Numarası.
        /// </summary>
        public static string RowNo {
            get {
                return ResourceManager.GetString("RowNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Günü.
        /// </summary>
        public static string SelectedBirthDay {
            get {
                return ResourceManager.GetString("SelectedBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Ayı.
        /// </summary>
        public static string SelectedBirthMonth {
            get {
                return ResourceManager.GetString("SelectedBirthMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Yılı.
        /// </summary>
        public static string SelectedBirthYear {
            get {
                return ResourceManager.GetString("SelectedBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri No.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        public static string SexId {
            get {
                return ResourceManager.GetString("SexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abone Numarası.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi No.
        /// </summary>
        public static string TaxNo {
            get {
                return ResourceManager.GetString("TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergi Dairesi.
        /// </summary>
        public static string TaxOffice {
            get {
                return ResourceManager.GetString("TaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Kimlik Numarası.
        /// </summary>
        public static string TCKNo {
            get {
                return ResourceManager.GetString("TCKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Ünvanı.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticaret Sicil Numarası.
        /// </summary>
        public static string TradeRegistrationNo {
            get {
                return ResourceManager.GetString("TradeRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilt Numarası.
        /// </summary>
        public static string VolumeNo {
            get {
                return ResourceManager.GetString("VolumeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut Hizmet Numarası.
        /// </summary>
        public static string XDSLNo {
            get {
                return ResourceManager.GetString("XDSLNo", resourceCulture);
            }
        }
    }
}
